### ISSUE TITLE
Remove vars in info.yml

### ISSUE THREAD

**Issue by Sanqui** [pyvec/naucse.python.cz#167]
It's redundant, these things should just be top-level.

```yaml
title: MI-PYT
description: Základy již znáte a chcete se dozvědět o dalších možnostech využití Pythonu.
long_description: [snip]
base_collection: intro
vars:
  canonical: true
  coach-present: false
  mi-pyt: true
```
into
```yaml
title: MI-PYT
description: Základy již znáte a chcete se dozvědět o dalších možnostech využití Pythonu.
long_description: [snip]
base_collection: intro
canonical: true
coach-present: false
```
