### ISSUE TITLE
Znak $ na začátku příkazů

### ISSUE THREAD

**Issue by messa** [pyvec/naucse.python.cz#194]
Začátečníci copypastují věci z návodu i s tím znakem dolaru na začátku, což pak samozřejmě nefunguje.

Nevím teď úplně, jak to řešit. Někdo nějaký nápad? :)

**Comment by kvbik** [comment]
hezky by bylo, kdyby to byl takovy ten znak, co se nepridava do copy/paste oznaceni. ale ani nevim, jak se to presne dela a uz vubec ne, jestli to konkretni formatovani `naucse` umi :))

**Comment by kvbik** [comment]
kazdopadne sice vsude ten `$` pisu taky, aby  z toho bylo jasne, ze to je shell command, ale vlastne je to z hlediska UX neprijemny i pro ne-zacatecnika.

**Comment by hroncok** [comment]
Až zjistíme, jak se to v HTML + CSS dělá, tak by neměl být problém to naučse implementovat.

**Comment by hroncok** [comment]
Takhle to vypadá zatím:

```html
<div class="highlight"><pre><span></span><span class="gp">$</span> python -m ensurepip --version
<span class="go">pip 9.0.1 (nebo i jiná verze)</span>
</pre></div>
```

**Comment by messa** [comment]
Šlo by to takhle: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

Aplikovat na tu class `gp` (což by mělo znamenat `Generic.Prompt`), nebo přinejhorším ohnout plugin v markdownu.

**Comment by hroncok** [comment]
Zkusím si to.

**Comment by kvbik** [comment]
porad mam pocit, ze nekde se tak deje defaultne, ne? neco jako v `ul/li` nebo v nejaky formatovani `pre` - ale googlil jsem a taky nachazel jenom tyhle `user-select`

**Comment by hroncok** [comment]
implementace, která umí tohle, je triviální:

![_](https://user-images.githubusercontent.com/2401856/30640346-d70d6aa4-9e02-11e7-8fa7-a2d920ba8016.png)
![_](https://user-images.githubusercontent.com/2401856/30640357-e18d27bc-9e02-11e7-9bf6-bd644964add6.png)

Pokud bychom chtěli, aby nebyla označená ani ta mezera, tak by to bylo složitější (musely bychom podědit  ` console` lexer podle mě).

**Comment by kvbik** [comment]
to `unselectable` funguje. a mozna by to chtelo pridat i tu mezeru za `$`

```html
<pre class="gp unselectable">$ </span>pip install bla
```

**Comment by kvbik** [comment]
byls rychlejsi @hroncok :) 👍

**Comment by benabraham** [comment]
Případně tam ten znak generujte přes generovaný obsah 
a) nebude ve zdrojáku 
b) nepůjde kopírovat

Nevím jestli se to řešení netluče s nějakým dalším záměrem (tisk knihy apod.)

```css
.whatever::before { 
    content: "$"; 
    …
}
```

**Comment by messa** [comment]
Nějak přes `<li class="line" prefix="$">sudo ...</li>` to mají v [tutorialech na digitalocean.com](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-with-http-2-support-on-ubuntu-16-04). Asi je to pak díky tomuto CSS magicu, který nakonec taky jen používá user-select:

```css
pre .prefixed{
white-space:normal;
margin:0;
font-size:14px!important
}
pre .line{
padding:0!important;
list-style-type:none!important;
white-space:pre;
margin:0 0 0 -5px!important;
line-height:1.5!important}
pre .line::before {
-webkit-user-select:none;
-moz-user-select:none;
-ms-user-select:none;
-o-user-select:none;
user-select:none;
content:attr(prefix);
text-align:right;
display:inline-block;
margin-right:10px;
margin-left:5px
}
```
