### ISSUE TITLE
allow base + extra materials

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#205]
In run, currently, I can either use base without materials (will use materials form base) or define my own list of materials. I'd like to define materials as addition to base's materials.

Instead of this:

```yaml
derives: pyladies
...
- base: loops
  date: 2017-10-03
  materials:
  - lesson: beginners/functions
    type: lesson
  - lesson: intro/turtle
    type: lesson
  - lesson: beginners/while
    type: lesson
  - title: Tahák s užitečnými funkcemi
    url: https://github.com/pyvec/cheatsheets/raw/master/basic-functions/basic-functions-cs.pdf
    type: cheatsheet
  - title: Domácí projekty (PDF)
    url: https://github.com/PyLadiesCZ/pyladies.cz/raw/master/original/v1/s003-looping/handout/handout3a.pdf
    type: homework
```

I want to do (something like):

```yaml
derives: pyladies
...
- base: loops
  date: 2017-10-03
  extra_materials:
  - title: Domácí projekty (PDF)
    url: https://github.com/PyLadiesCZ/pyladies.cz/raw/master/original/v1/s003-looping/handout/handout3a.pdf
    type: homework
```
