### ISSUE TITLE
Allow empty material entry (lessons with titles only)

### ISSUE THREAD

**Issue by hroncok** [pyvec/naucse.python.cz#207]
There are empty material entries on pyladies.cz, but i couldn't find a way to do it here. If I provide no URL, no lesson attribute, it's invalid Material:

```yaml
  - title: MicroPython a malé počítače
    type: lesson
``` 

```pycon
ValueError: Unknown material type: {'type': 'lesson', 'title': 'MicroPython a malé počítače'}
```

I had to use this as a workaround:

```yaml
  - title: MicroPython a malé počítače
    type: lesson
    url: '#'
```
